# Generated by Django 3.1.1 on 2020-10-06 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20201004_0654'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='currecny',
            new_name='currency',
        ),
    ]
