# Generated by Django 3.1.2 on 2020-10-14 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_auto_20201014_0216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='room_type',
        ),
        migrations.AddField(
            model_name='room',
            name='room_type',
            field=models.ManyToManyField(null=True, related_name='rooms', to='rooms.RoomType'),
        ),
    ]
